# group: Keycloak
# @name get-user-password-token

POST http://localhost:8080/realms/users/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type = password &
client_id = backend-client &
username = esther_swaniawski49@mail.ru &
password = password
