apiVersion: v1
kind: Service
metadata:
  name: keycloak
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080  # Optional: specify a NodePort or let Kubernetes assign one
  selector:
    app: keycloak