CREATE TABLE USERS (
   id BIGSERIAL PRIMARY KEY,
   user_id UUID NOT NULL UNIQUE,
   username VARCHAR(255) NOT NULL UNIQUE
);

GRANT ALL PRIVILEGES ON TABLE USERS TO backend_user;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO backend_user;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO backend_user;
