START TRANSACTION ;

CREATE TABLE GROUP_ACCESS_TOKENS (
     id SERIAL PRIMARY KEY,
     group_id UUID NOT NULL,
     access_token TEXT NOT NULL UNIQUE,
     created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

GRANT ALL PRIVILEGES ON TABLE GROUP_ACCESS_TOKENS TO backend_user;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO backend_user;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO backend_user;

COMMIT ;