###
# @name reset-password
POST http://localhost:8090/public/api/v1/authentication/reset-password
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "username": "felipe_hintz@mail.ru",
  "password": "password"
}
