server:
  port: 8090

spring:
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://localhost:5432/backend?currentSchema=public
    username: backend_user
    password: password
    driverClassName: org.postgresql.Driver
  sql:
    init:
      mode: NEVER
      platform: postgres
      schema-locations: classpath:schema.sql
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/users


logging:
  level:
    root: info
    ru: debug

keycloak:
  serverUrl: http://localhost:8080
  realm: users
  clientId: backend-client
  adminUsername: users-admin
  adminPassword: password