server:
  port: 8090

spring:
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://localhost:5432/backend
    username: backend_user
    password: password
    driverClassName: org.postgresql.Driver
  sql:
    init:
      platform: postgres
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/users