###
# @name Create Infitite Job
POST http://localhost:8090/api/v1/job
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "name": "testjob-{{$randomAlphaNumeric}}{{$randomAlphaNumeric}}{{$randomAlphaNumeric}}{{$randomAlphaNumeric}}{{$randomAlphaNumeric}}",
  "dockerImage": "busybox",
  "command": ["sh", "-c", "while true; do echo 'Container is running'; sleep 10; done"],
  "environmentVariables": {},
  "executionType": "ON_DEMAND"
}
