###
# @name Create Demand Job
POST http://localhost:8090/api/v1/job
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "name": "job-{{$random.address.cityName}}-{{$random.ancient.god}}",
  "groupId": "{{group-id}}",
  "dockerImage": "busybox",
  "command": ["sh", "-c", "echo 'Container is running'"],
  "environmentVariables": {},
  "executionType": "ON_DEMAND"
}