###
# @name Create Demand Job
POST http://localhost:8090/api/v1/job
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "name": "cite-{{$random.address.cityName}}",
  "dockerImage": "ubuntu",
  "command": ["curl -s https://api.chucknorris.io/jokes/random | jq -r '.value'"],
  "environmentVariables": {},
  "executionType": "ON_DEMAND"
}