###
# @name Exclude Member
POST http://localhost:8090/api/v1/role-model/exclude-member-from-group
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "groupId": "{{group-id}}",
  "memberId": "{{group-member-id}}"
}
