run ../../keycloak/get-user-token-via-token-exchange.http

###
# @name Get Join Group Token
GET http://localhost:8090/api/v1/role-model/get-join-group-token/{{group-id}}
Authorization: Bearer {{access_token}}

> {%
    client.test("Status is ok", function () {
        client.assert(response.status == 200, "Status in not ok")
    })
    client.global.set("join-group-token", response.body["token"])
 %}