###
# @name Join Group
POST http://localhost:8090/api/v1/role-model/join-group
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "token": "YmIxOTNmMjctMzU3NC00MTk2LTkzNzctMmY5NTkxOGY0NzAw"
}